-- What is require to improve the debug
-- A single configuration, dinamicaly generate when start the debugging
-- keybinding to add breakpoint
-- continue
-- step over
-- step into
-- step out
--
--
-- nnoremap <silent> <F5> :lua require'dap'.continue()<CR>
-- nnoremap <silent> <F10> :lua require'dap'.step_over()<CR>
-- nnoremap <silent> <F11> :lua require'dap'.step_into()<CR>
-- nnoremap <silent> <F12> :lua require'dap'.step_out()<CR>
-- nnoremap <silent> <leader>b :lua require'dap'.toggle_breakpoint()<CR>
-- nnoremap <silent> <leader>B :lua require'dap'.set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>
-- nnoremap <silent> <leader>lp :lua require'dap'.set_breakpoint(nil, nil, vim.fn.input('Log point message: '))<CR>
-- nnoremap <silent> <leader>dr :lua require'dap'.repl.open()<CR>
-- nnoremap <silent> <leader>dl :lua require'dap'.run_last()<CR>
-- help mapping
-- my idea is to have a function to generate the path of the configuration
--
--
-- local dap = require('dap')

-- dap.adapters.php = {
--   type = 'executable',
--   command = 'node',
--   args = { '/home/adalessa/repos/vscode-php-debug/out/phpDebug.js' }
-- }

-- dap.configurations.php = {
--   {
--     type = 'php',
--     request = 'launch',
--     name = 'Listen for Xdebug',
--     port = 9003,
--     pathMappings = {
--         ['/app'] = '/home/adalessa/code/php/carin-gateway-service'
--     }
--   }
-- }
-- the problem is the path mapping maybe just have that updated by project base
-- maybe have it as a resolve function of the path when open, need to test
  require('dap.ui.widgets').hover()
