-- I want to improve a quality of life on controllers
-- Want to show the uri beside de controller
-- Why just stetics
--
-- Give a warning if the controller is missing some assigned routes
--

-- Snippet for creating relationships
-- A select node for the type of relation on the return type
-- base on that node which function should call
-- base on the name and type create the name??
